add Fuse support to FutureExt
smol-rs/futures-lite pull request #101
Opened 2024-05-08 07:30 UTC by GlenDC

Closes #100

2024-05-08 07:32 UTC, GlenDC commented
Ready for review @notgull

2024-05-08 14:36 UTC, notgull requested changes

2024-05-08 14:36 UTC, notgull commented on src/future.rs
> +            }),
I'd prefer to move the `map`ping of `poll` to the expression being `match`ed on.

2024-05-08 14:36 UTC, notgull commented on src/future.rs
> +    }
I would prefer a freestanding function instead of a member of the trait.

2024-05-08 17:18 UTC, GlenDC commented on src/future.rs
> +            }),
Can you elaborate? Not sure I follow.

2024-05-08 20:57 UTC, GlenDC commented on src/future.rs
> +            }),
Ok @notgull I think I applied what you wanted here, but do let me know if that's still not what you were looking for here.

2024-05-09 00:40 UTC, notgull requested changes

2024-05-09 00:40 UTC, notgull commented on src/future.rs
> +            })
```suggestion
        match self.as_mut().project().inner.as_pin_mut().map(|f| f.poll(cx)) {
            Some(Poll::Ready(output)) => {
                self.project().inner.set(None);
                Poll::Ready(output)
            }
            
            Some(Poll::Pending) | None => Poll::Pending
        }
```

Apologies, I was on the train. I was moreso hoping for this

2024-05-10 18:36 UTC, GlenDC commented on src/future.rs
> +            })
Cool. Looks good.

2024-05-11 02:09 UTC, notgull approved these changes
Thanks!

2024-05-11 02:10 UTC, merged