feat: add `StreamExt::take_until`.
smol-rs/futures-lite pull request #103
Opened 2024-05-27 01:59 UTC by LebranceBW

This commit migrates `Stream::take_until` from futures into futures-lite with little modification. 
version are also updated.

2024-05-27 18:14 UTC, notgull requested changes
I don't think this is possible with the current set of combinators, so I think it's worth accepting this PR.

2024-05-27 18:14 UTC, notgull commented on CHANGELOG.md
> +# Version 2.4.0
Don't add entries to the CHANGELOG or bump the version, I do that myself when I release a new version.

2024-05-27 18:14 UTC, notgull commented on src/stream.rs
> +    fn take_until<F>(self, future: F) -> TakeUntil<Self, F>
I would prefer this as a free function, rather than a member of the trait.

2024-05-27 18:14 UTC, notgull commented on src/stream.rs
> +            fut: future.into(),
Avoid ambiguity and do `Some(future)`.

2024-05-28 00:31 UTC, LebranceBW commented on src/stream.rs
> +    fn take_until<F>(self, future: F) -> TakeUntil<Self, F>
I will move it out of this trait, but I'd remind you that `futures` library take it as a member of `StreamExt`

2024-05-28 00:53 UTC, notgull requested changes

2024-05-28 00:53 UTC, notgull commented on src/stream.rs
> +    /// The future is returned only if it isn't resolved yet, ie. if the stream isn't stopped yet.
```suggestion
    /// Extract the stopping future out of the combinator.
    /// 
    /// The future is returned only if it isn't resolved yet, ie. if the stream isn't stopped yet.
```

2024-05-28 00:53 UTC, notgull commented on src/stream.rs
> +    ///
```suggestion
```

2024-05-28 00:53 UTC, notgull commented on src/stream.rs
> +        self.stream.size_hint()
Wouldn't it be more correct for the lower bound of the size hint to always be zero? Since the stream could be stopped after `size_hint` is called.

2024-05-28 01:10 UTC, LebranceBW commented on src/stream.rs
> +        self.stream.size_hint()
> Wouldn't it be more correct for the lower bound of the size hint to always be zero? Since the stream could be stopped after `size_hint` is called.

You are right.  stream can be stopped at any time, and it's lower bound isn't reliable anymore.

2024-05-28 01:49 UTC, notgull approved these changes
Thanks!

2024-05-28 01:50 UTC, merged