Add list of excluded features
smol-rs/futures-lite pull request #112
Opened 2024-11-03 00:06 UTC by notgull

This commit adds a list of features that have been determined to be out
of scope for `futures-lite`. The intent of this list is to inform users
which features `futures-lite` does not implement, as well as potential
contributors which PRs will not be accepted.

cc #111

cc @smol-rs/admins Please give me feedback on this document.

2024-11-03 07:05 UTC, stackinspector commented
Thoughts about the 'ideal' `Sink` API: In my view this API is certainly ideal with cases where IO is not involved like channels. But for IO-involved cases, an error type is reasonable, and it can be considered to take the object to send as a reference. So should it be 2 APIs?

2024-11-03 12:43 UTC, zeenix requested changes
Nice! 😎 LGTM otherwise but I am not sure a file in the repo will have sufficient visibility. I think most (all?) of this should be part of the crate docs or at least linked from there.

2024-11-03 15:53 UTC, taiki-e requested changes

2024-11-03 15:53 UTC, taiki-e commented on FEATURES.md
> +[`futures-concurrency`] provides a number of simple APIs for dealing with
I'm hesitant to officially recommend this crate because there was a lot of suspicious unsafe code when I looked at it before.
https://github.com/rust-lang/futures-rs/issues/2851#issuecomment-2066826865

2024-11-03 15:53 UTC, taiki-e commented on FEATURES.md
> +not broken to the point that [`Sink`]'s is.*
I honestly don't think async fn in trait is the right solution (e.g., see https://github.com/rust-lang/rfcs/pull/3710#issuecomment-2439892122).

2024-11-03 15:53 UTC, taiki-e commented on FEATURES.md
> +    async fn send(&mut self, object: T) -> Result<(), T>;
This particular API will not work well in cases where it is not easy to recover the original data on send failure or where it is necessary to know the cause of the failure.

2024-11-03 15:53 UTC, taiki-e commented on FEATURES.md
> +infallible, like channels. In addition the multi-call requirement makes the API
> where the [`Sink`] is infallible, like channels.

channel send is fallible...
https://docs.rs/async-channel/2.3.1/async_channel/struct.SendError.html

2024-11-03 15:53 UTC, taiki-e commented on FEATURES.md
> +  [`oneshot`] provides an asynchronous oneshot channel.
async-channel has an optimization to handle single capacity case well, and I think it is also okay to use it for oneshot case.

2024-11-03 16:01 UTC, taiki-e commented
As for alternatives to Sink, there was some discussion about something like AsyncExtend (async-std has it but inefficient since that requires boxing).

(Personally, I have the impression that Sink has (potential) users with a variety of different requirements, that there is not yet a solution that sufficiently meets them, and that abstraction is often not actually needed there in the first place.)

2024-11-03 17:50 UTC, stackinspector commented on FEATURES.md
> +  [`oneshot`] provides an asynchronous oneshot channel.
First time I've heard of it! I'll give it a try.

2024-11-03 20:37 UTC, fogti requested changes

2024-11-03 20:37 UTC, fogti commented on FEATURES.md
> +This document aims to describe all intentional feature occlusions are provide
`to describe` and `are` don't grammatically mix well together, perhaps a comma is missing.

2024-11-03 20:37 UTC, fogti commented on FEATURES.md
> +First of all it is  significantly simpler to implement. Since we don't need to
```suggestion
First of all, it is significantly simpler to implement. Since we don't need to 
```

2024-11-03 20:37 UTC, fogti commented on FEATURES.md
> +infallible, like channels. In addition the multi-call requirement makes the API
unbounded channels?

2024-11-04 08:15 UTC, taiki-e commented on FEATURES.md
> +infallible, like channels. In addition the multi-call requirement makes the API
unbounded channel send returns an error if closed.

2024-11-08 04:42 UTC, notgull commented on FEATURES.md
> +[`futures-concurrency`] provides a number of simple APIs for dealing with
cc @yoshuawuyts 

I think it's better now, but I'm not sure, I haven't fully reviewed the code.

2024-11-08 04:42 UTC, notgull commented on FEATURES.md
> +not broken to the point that [`Sink`]'s is.*
Personally I disagree. In fact `async-io` basically supports the "N readers N writers" use case without much needed changes. Not to mention `AsyncRead` and `AsyncWrite` in their current state are problematic because they don't support completion based APIs like `io_uring`.

2024-11-08 04:42 UTC, notgull commented on FEATURES.md
> +  [`oneshot`] provides an asynchronous oneshot channel.
My understanding is that `async-channel` requires an additional allocation for oneshot channels over the [`oneshot`] crate.

2024-11-08 04:43 UTC, notgull commented on FEATURES.md
> +    async fn send(&mut self, object: T) -> Result<(), T>;
I've removed this section to remain slightly more unopinionated.

2024-11-11 18:28 UTC, zeenix commented
@notgull I only raised one concern, which didn't get addressed?

2024-11-12 03:00 UTC, notgull commented
I missed that one @zeenix, I've added a link to the future `FEATURES.md` to the docs for `futures-lite`.

2024-11-12 09:11 UTC, zeenix requested changes
:+1:

2024-11-12 09:11 UTC, zeenix commented on src/lib.rs
> +//! [features list]: https://github.com/smol-rs/futures-lite/blob/master/FEATURES.md
Thanks! Sorry to ask for more but could you please also add this to the README? 

Reminds me that we should make use of `#![doc = include_str!("../README.md")]` to avoid duplication and keeping the crate docs and README in sync manually.

2024-11-12 13:06 UTC, fogti approved these changes

2024-11-16 20:21 UTC, notgull commented on src/lib.rs
> +//! [features list]: https://github.com/smol-rs/futures-lite/blob/master/FEATURES.md
I've added this.

2024-11-17 14:51 UTC, zeenix approved these changes

2024-11-23 19:13 UTC, merged