Add a combinator for temporarily using an AsyncRead/AsyncWrite as Read/Write
smol-rs/futures-lite pull request #62
Opened 2022-11-06 04:56 UTC by notgull

During smol-rs/async-rustls#9, @zseri pointed out that [we frequently use a type that just converts an `AsyncRead` to a `Read`](https://github.com/smol-rs/async-rustls/pull/9#discussion_r1008779510) temporarily so that it can be used in `rustls`, which only takes a `Read`. This pattern is not unique to `async-rustls`, since I've also seen this used in `tokio-tungstenite`, following a similar pattern.

In order to deduplicate instances of this pattern throughout the ecosystem, this PR implements this pattern as a type in the `io` module.

2022-11-06 16:39 UTC, notgull commented
Clippy error is unrelated to this PR, see #63

2022-11-06 18:30 UTC, zseri requested changes

2022-11-06 18:30 UTC, zseri commented on src/io.rs
> +}
these methods should be `#[inline]`

2022-11-06 18:30 UTC, zseri commented on src/io.rs
> +}
instead of dozens of "dumb" setters/getters, maybe just make the fields `pub` ? It's an "unusual case wrapper" anyways, so that might also reduce downstream friction.

2022-11-06 18:30 UTC, zseri commented on src/io.rs
> +    pub fn into_inner(self) -> (&'r mut Context<'ctx>, T) {
If this would be kept, rename to `into_parts` for consistency with libstd.

2022-11-06 18:30 UTC, zseri commented on src/io.rs
> +    fn poll_with<R>(
idk it might be a good idea to make this `pub`.

2022-11-06 18:30 UTC, zseri commented on src/io.rs
>  }
could you omit these `#[inline]`'s please? (I'll probably do a PR which refactors these to reduce the code duplication there)

2022-11-06 18:42 UTC, notgull commented on src/io.rs
> +}
I avoid having `pub` fields, because it means that any change to the layout, representation or the fields of the structure (including adding some) becomes a breaking change.

2022-11-06 21:50 UTC, zseri commented on src/io.rs
> +}
well, but with `into_parts`, changing the amount of fields would be already a breaking change if propagated, and a break of conventions otherwise. The only thing I could imagine would be an introduction of an additional wrapper around `T`, but I don't think that's likely.

2022-11-06 23:30 UTC, notgull commented on src/io.rs
> +}
You know what, you're probably right. I've reimplemented it so it's `pub`.

2022-11-07 00:51 UTC, zseri commented on src/io.rs
> +        AsyncAsSync { context, inner: io }
```suggestion
    pub fn new(context: &'r mut Context<'ctx>, inner: T) -> Self {
        AsyncAsSync { context, inner }
```

2022-11-07 08:13 UTC, zseri approved these changes

2022-11-07 08:26 UTC, merged