v2.0.0
smol-rs/futures-lite pull request #78
Opened 2023-09-25 16:16 UTC by notgull

- **Breaking:** Expose `future::{ready, pending}` from `std` instead of defining our own. (#73)
- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
- Add a way to use racey futures on `no_std` by providing your own seed. (#75)

2023-09-26 16:19 UTC, fogti commented
#73: we import them from `core`, not `std`, right?

2023-10-18 04:15 UTC, notgull commented
> #73: we import them from `core`, not `std`, right?

Correct, fixed!

2023-10-24 15:13 UTC, notgull commented
@smol-rs/admins Any chance this release can be reviewed?

2023-10-24 15:45 UTC, zeenix requested changes
LGTM otherwise.

2023-10-24 15:45 UTC, zeenix commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
nit: way too long a line. Let's break at 100 chars, like we do for code.

2023-10-24 15:50 UTC, taiki-e commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
Considering how the markdown is rendered in the GitHub release, I personally prefer not to use the hard wrap in the middle of a sentence in changelog.

2023-10-24 16:01 UTC, zeenix commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
if the tooling is broken, we should fix the tooling, not workaround it with huge lines. At least it's not like the silly practice of starting every sentence on a new line. :)

2023-10-24 16:21 UTC, taiki-e commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
I meant basically no wrap, not wrap every sentence.

2023-10-24 16:26 UTC, taiki-e commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
(BTW, the way the markdown is rendered in the GitHub release is the same one used in comments in GitHub we are currently writing.)

2023-10-24 16:47 UTC, zeenix commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
> I meant basically no wrap, not wrap every sentence.

I understood. You can safely ignore that sentence of mine. :)

> (BTW, the way the markdown is rendered in the GitHub release is the same one used in comments in GitHub we are currently writing.)

Then I'm not sure I understand what the problem is? :thinking:

2023-10-25 03:23 UTC, notgull commented on CHANGELOG.md
> +- **Breaking:** The `TryZip` and `Zip` combinators are modified to have a cleaner API, where generic constraints are not necessary on the structure itself at the cost of additional generics. (#74)
Agreed with @zeenix

2023-10-25 10:19 UTC, zeenix approved these changes

2023-10-25 15:38 UTC, merged